name: Atualizar Vagas Diariamente

on:
  schedule:
    - cron: '0 12 * * *'  # Roda todo dia às 09h Brasil (12 UTC)
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Instalar dependências do Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libasound2

      - name: Rodar Scraper
        run: node scraper.js

      - name: Commit automático
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Atualização automática de vagas"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}